/* Generated by tools/bake_content.py from written.html. Do not edit.
 *
 * The document site is the source of every word and every number in
 * here. Editing this file instead of the page puts a second copy of a
 * measurement in the repository, which is how a figure ends up corrected
 * in one place and wrong in the other. Change written.html and re-run the
 * baker. */
export const CONTENT = {
 "about": [
  "I write the software that decides where a robot goes next, and the bringup that gets it onto real hardware. Global planners, local controllers, reactive replanning for manipulators — most of it started as someone else’s published method, checked against its own paper or a reference implementation, then fixed where it didn’t hold up.",
  "Right now that means physical AI: learned policies for bimanual manipulation, moved off the simulator and onto a UR12e. Before Northeastern it was five seasons with Team Robocon MJCET, building robots that had to work on a specific day in front of a judge, which is its own kind of benchmark."
 ],
 "work": [
  {
   "title": "Bimanual deformable garment manipulation",
   "desc": "Trained and evaluated ACT, Diffusion Policy and smolVLA on multi-garment folding in a bimanual setup in Isaac Sim, alongside work with π0, π0.5 and OpenPI across the VLA stack. Sim-to-real transfer onto a UR12e is in progress.",
   "chips": [
    "Isaac Sim",
    "π0 / π0.5",
    "OpenPI",
    "ACT",
    "Diffusion Policy",
    "smolVLA"
   ],
   "stats": [
    {
     "k": "Success rate",
     "v": "60.4%"
    },
    {
     "k": "Peak, long top",
     "v": "78%"
    },
    {
     "k": "Categories",
     "v": "4"
    }
   ]
  },
  {
   "title": "Pick and place that replans around what the camera sees",
   "desc": "UR12e and a Robotiq Hand-E. A RealSense depth pipeline with workspace filtering, robot self-masking and colour-based body exclusion isolates live obstacles, so when a hand enters the planned path the controller cancels cleanly, waits for the arm to settle and re-plans from the current state.",
   "chips": [
    "ROS 2 Jazzy",
    "MoveIt 2",
    "BIT*",
    "RealSense D435i",
    "OctoMap"
   ],
   "stats": [
    {
     "k": "Detection",
     "v": "100% ≥4 cm"
    },
    {
     "k": "Detect latency",
     "v": "0.10s"
    },
    {
     "k": "Blind within",
     "v": "11cm"
    },
    {
     "k": "IK solution pool",
     "v": "120"
    }
   ]
  },
  {
   "title": "Reactive autonomous navigation stack",
   "desc": "A planner/controller architecture written from scratch for TurtleBot4 — no Nav2 behaviour tree server. A*, Theta*, SMAC and RRT sit behind one global interface; DWA, Pure Pursuit, Stanley, TEB and MPPI behind another, all five driving the same suite closed-loop. The C++ port is benchmarked below.",
   "chips": [
    "ROS 2 Jazzy",
    "C++",
    "TurtleBot4",
    "nav2_costmap_2d"
   ],
   "stats": [
    {
     "k": "Global planners",
     "v": "4"
    },
    {
     "k": "Local controllers",
     "v": "5"
    },
    {
     "k": "A* after C++ port",
     "v": "99–192×"
    }
   ]
  },
  {
   "title": "K.A.L.B — kinematical autonomous legged robot",
   "desc": "A twelve-axis quadruped with locomotion modelled after the MIT Cheetah. Gait stability and autonomous navigation validated with SLAM in Gazebo. Now collecting locomotion and obstacle-avoidance demonstrations for inverse reinforcement learning, aimed at a Unitree Go2.",
   "chips": [
    "ROS 2",
    "Gazebo",
    "gmapping",
    "AMCL",
    "Inverse RL"
   ],
   "stats": [
    {
     "k": "Actuated axes",
     "v": "12"
    },
    {
     "k": "Legs",
     "v": "4"
    },
    {
     "k": "Gait",
     "v": "Trot"
    }
   ]
  },
  {
   "title": "Custom DWA local planner",
   "desc": "The dynamic window approach written from scratch instead of pulling in nav2_dwb_controller — velocity sampling inside the dynamic constraints, trajectory rollout, cost evaluation on goal distance and clearance, and an RViz marker for every candidate so you can see what it rejected.",
   "chips": [
    "ROS 2 Humble",
    "TurtleBot3",
    "RViz"
   ],
   "stats": [
    {
     "k": "GitHub stars",
     "v": "6"
    },
    {
     "k": "Written from",
     "v": "Scratch"
    }
   ]
  },
  {
   "title": "Robot foundation model",
   "desc": "A flow-matching VLA, a latent world model and an RL-tuned reasoner on one backbone, with an orchestration layer above it that never touches the weights — models/ does not import orchestration/, which is what keeps two philosophies from being stapled together. Every robot writes into one 32-D action space with a per-embodiment mask, and a competence head exports abstention so the layer above can ask “can you do this?” in a forward pass instead of a rollout. It trains on 3,008 episodes collected in robosuite and it has never once completed the task — 0 of 16. The one real result is the competence signal: prediction error separates failures at AUROC 0.946 ± 0.008 against controls at 0.11, which the repo still refuses to call a win because the same checkpoint predicts the next latent worse than copying the present. Its own evidence index opens by counting twelve times a number looked healthy while the thing it stood for did nothing.",
   "chips": [
    "PyTorch",
    "Flow matching",
    "GRPO",
    "Pydantic",
    "RDT-style action space"
   ],
   "stats": [
    {
     "k": "Action space",
     "v": "32-D"
    },
    {
     "k": "Embodiments",
     "v": "7"
    },
    {
     "k": "Failure modes watched",
     "v": "9"
    }
   ]
  },
  {
   "title": "Orchestrated bimanual assembly",
   "desc": "The same instrument stack — latent world model, calibrated competence head, RL-tuned reasoner, Conductor and harness — driving a LoRA-finetuned π0.5 on the NIST Assembly Task Board in Isaac Sim, two UR5s on a shared workspace. The question is narrow on purpose: does the instrument stack earn its place with the policy and the task held fixed, harness on against harness off. Nothing broader. The muscle changes and the instruments do not — they are ported by import, so there is one definition of copy_margin rather than two that will drift, and “ported wholesale” is a claim you can check with grep. Eight of the fourteen tensor widths change in the swap and three agree by luck, which is exactly when an unasserted assumption survives, so all fourteen are asserted and printed at run start. Six phases, each gated by a passing artefact the CLI checks rather than by discipline; the reasoner GRPO phase is the highest-risk one and has never run.",
   "chips": [
    "Isaac Sim",
    "π0.5 / openpi",
    "LoRA",
    "GRPO",
    "ROS 2",
    "UR5 × 2"
   ],
   "stats": [
    {
     "k": "Gated phases",
     "v": "6"
    },
    {
     "k": "Tensor widths asserted",
     "v": "14"
    },
    {
     "k": "P0 gate",
     "v": ">90%"
    }
   ]
  },
  {
   "title": "Quadruped navigation cost, and the constant that faked it",
   "desc": "Four cost functions for a Unitree Go2 — default Nav2 inflation, a hand-tuned legged costmap, a supervised learned cost and maximum-entropy IRL — sharing one planner, one controller and one 120-course suite so that only the cost function varies. The first table showed Nav2 losing decisively at 70.0%, with 20 of its 36 failures being slips on ice an occupancy costmap has no channel to represent. It came from FALL_RATE, a constant in my own simulator I had tuned by hand until the methods separated. A MuJoCo cross-check against the real Go2 MJCF found the drag sign backwards — ice is the slowest surface at 0.30, not the fastest at 0.95 — and no falls at all on flat low-friction ground. With the invented hazard removed, Nav2 goes to 87.5% and the effect disappears. All four are now indistinguishable and every interval overlaps. Everyone building a robot-learning evaluation writes a surrogate like this; almost nobody validates it, and the null result is the evidence for doing so.",
   "chips": [
    "MuJoCo",
    "Nav2",
    "MaxEnt IRL",
    "PyTorch",
    "Unitree Go2",
    "ROS 2"
   ],
   "stats": [
    {
     "k": "Courses",
     "v": "120"
    },
    {
     "k": "Nav2, before → after",
     "v": "70.0 → 87.5%"
    },
    {
     "k": "MuJoCo cross-check",
     "v": "33× realtime"
    }
   ]
  },
  {
   "title": "One workcell, three simulators, and a false agreement",
   "desc": "Two UR5e arms over a shared bench, a Robotiq Hand-E on each and four RealSense cameras. The cell is described once in xacro and emitted as MJCF, SDF and USD, so MuJoCo, Gazebo and Isaac Sim run the same robot instead of three that drift. cell-verify compares the three link by link and gates on 44 checks. I had a section here claiming the two engines agreed on a pick-and-place task, six numbers within 2.8 %. They did not. Running the same detector on the poses the layout file declares, with no simulator and no contact, reproduced Gazebo’s whole column to 0.1 mm, and MuJoCo’s spread turned out to be its own spawn jitter. So I logged every contact across the 650-step run: the tools only ever touch the bench. Both engines were scoring three objects lying still. The real result is narrower. The descriptions match to 0.1 mm, and no tolerance here has been checked against a contact model yet.",
   "chips": [
    "MuJoCo",
    "Gazebo",
    "Isaac Sim",
    "MoveIt 2",
    "USD / SDF / MJCF",
    "UR5e × 2"
   ],
   "stats": [
    {
     "k": "Cross-simulator checks",
     "v": "44"
    },
    {
     "k": "Descriptions, one source",
     "v": "3"
    },
    {
     "k": "Arm-to-tool contacts, 650 steps",
     "v": "0"
    }
   ]
  },
  {
   "title": "Two ways to let a model write the policy",
   "desc": "Graph-as-Policy is the target, but it runs as a separate process and wants an RTX 4090, an API key and 3.5 GB of weights. This pod has no GPU at all, so no graph has produced an episode here. Code as Policies has the same shape — an instruction goes in, a policy comes out — but what it emits is text, so it runs anywhere. A generator writes Python against a small API, a sandbox executes it under bounded names, calls and wall clock, and the workcell’s own primitives do every motion. Only the choice of sequence changes between that and the scripted expert, which is what makes the two comparable at all. Each episode stores the exact program that drove it and checks it against its digest before running. The measured result is negative: containment fell from 1 of 3 to 0 of 3. That was the workcell’s 82 commits rather than the policy, and it took a control run on each revision to tell them apart.",
   "chips": [
    "Code as Policies",
    "Graph as Policy",
    "Physical AI",
    "MuJoCo",
    "Pydantic",
    "UR5e × 2"
   ],
   "stats": [
    {
     "k": "Episodes from a graph",
     "v": "0"
    },
    {
     "k": "Containment, across the bump",
     "v": "1 → 0 of 3"
    },
    {
     "k": "Runs to attribute one regression",
     "v": "3"
    }
   ]
  }
 ],
 "measured": {
  "lede": [
   "Claims I could check, checked — including the ones that came out badly."
  ],
  "tables": [
   {
    "title": "A* global planner",
    "note": "Median of five runs on 8-connected costmaps.",
    "head": [
     "Map",
     "Python",
     "C++",
     "Speedup",
     "Relative (log)"
    ],
    "rows": [
     [
      "128 × 128",
      "7.50 ms",
      "0.046 ms",
      "163×"
     ],
     [
      "256 × 256",
      "110.26 ms",
      "1.115 ms",
      "99×"
     ],
     [
      "384 × 384",
      "884.21 ms",
      "4.598 ms",
      "192×"
     ]
    ],
    "tail": "Not all of that is the language. The C++ port also introduced a closed set, so it expands 21,015 nodes where Python expands 61,631 on the same map. Roughly 3× is algorithmic; the rest is a heapq of tuples against a priority_queue of PODs."
   },
   {
    "title": "DWA rollout and scoring",
    "note": "Median of 25 runs, 2.5 s horizon at dt = 0.1.",
    "head": [
     "Window",
     "Python",
     "C++",
     "Per traj.",
     "Relative (log)"
    ],
    "rows": [
     [
      "Accel-limited one control cycle, 36 traj. numpy / 30 C++",
      "0.3037 ms",
      "0.0098 ms",
      "26×"
     ],
     [
      "Full velocity space 2,626 trajectories",
      "4.2121 ms",
      "1.0570 ms",
      "4×"
     ]
    ],
    "tail": "The gap shrinks as the batch grows. At the window the controller actually evaluates each cycle, numpy pays fixed per-call overhead across a few dozen trajectories and loses by 26×. Give it 2,626 and vectorisation amortises that down to 4×. So the C++ port buys the most where it matters least — both clear a 20 Hz budget on the real window — and the global planner is where it earns its keep. The speedup column is per trajectory, which is why dividing the two times in the top row gives 31 rather than 26. The two sides do not sweep the same window: numpy builds it with arange against a stop of v_max + resolution, which admits one velocity sample past the limit the window is supposed to have, so it scores 36 candidates where the C++ loop's v <= v_max scores 30. Per trajectory is the honest comparison of the two implementations; it also means the numpy column is timing 20% more work than the label on the window claims."
   },
   {
    "title": "Obstacle detection — UR12e replanning",
    "note": "Synthetic frames with known ground truth, through the detector’s own callback.",
    "head": [
     "Obstacle radius",
     "Detected",
     "Centroid error",
     "Latency",
     "40 trials"
    ],
    "rows": [
     [
      "2 cm",
      "0 / 40",
      "—",
      "—"
     ],
     [
      "3 cm",
      "0 / 40",
      "—",
      "—"
     ],
     [
      "4 cm",
      "40 / 40",
      "2.3 mm",
      "0.10 s"
     ],
     [
      "6 cm",
      "40 / 40",
      "2.1 mm",
      "0.10 s"
     ],
     [
      "10 cm",
      "40 / 40",
      "2.1 mm",
      "0.10 s"
     ]
    ],
    "tail": "Below about 4 cm an object returns fewer points than the detector’s threshold and is never seen. Above it the thing saturates — size stops mattering, the centroid lands within ~2 mm of truth, and detection takes two frames at 20 Hz. Zero false positives in 300 frames with the arm in view. The pipeline runs in 2.47 ms against a 50 ms budget, so latency is set by the debounce counter, not by compute."
   },
   {
    "title": "…and where it goes blind",
    "note": "An obstacle walked in toward the forearm, 25 trials per distance.",
    "head": [
     "Distance to nearest link",
     "Detected",
     "25 trials"
    ],
    "rows": [
     [
      "11 cm",
      "76%"
     ],
     [
      "12 cm",
      "100%"
     ],
     [
      "30 cm",
      "100%"
     ]
    ],
    "tail": "This is the number worth knowing, and I would rather publish it than not. ARM_SEG_RADIUS carves a 12 cm tube around the kinematic chain and everything inside it is discarded as the robot’s own body — so a hand closer than about 11 cm to a link is invisible, not detected late. It is a deliberate trade against phantom detections off the arm itself, but it means the safety claim is “avoids what it can see”, and things within 11 cm are not in that set."
   },
   {
    "title": "Garment folding, against the literature",
    "note": "Published figures, each on its own task. Not a head-to-head.",
    "head": [
     "System",
     "Reported",
     "Measured on",
     "Source"
    ],
    "rows": [
     [
      "SpeedFolding Avigal et al., IROS 2022",
      "93%, <120 s per fold",
      "Real garments from a random initial configuration, engineered bimanual primitives, 4,300 annotated actions",
      "2208.10552"
     ],
     [
      "ACT Zhao et al., RSS 2023",
      "80–90%",
      "Six fine-grained bimanual tasks — battery slotting, condiment cup. Rigid objects",
      "2304.13705"
     ],
     [
      "smolVLA Hugging Face, 2025",
      "78.3%",
      "SO100 pick-place, stacking, sorting. Rigid objects",
      "blog"
     ],
     [
      "Diffusion Policy Chi et al., RSS 2023",
      "+46.9% over prior SOTA",
      "12 tasks across 4 manipulation benchmarks",
      "2303.04137"
     ]
    ],
    "tail": "Read this as context, not a leaderboard — no two rows share a task, a robot or a success criterion. Two things it does show. The 78–90% those architectures report is on rigid objects; none of it is deformables, which is the part that makes garments hard. And the one row that is garment folding, SpeedFolding at 93%, gets there with engineered bimanual action primitives and 4,300 annotated actions rather than an end-to-end learned policy. The distance between 60.4% and 93% is mostly that gap, and closing it is what the sim-to-real work is for."
   }
  ]
 },
 "stack": [
  {
   "k": "Frameworks",
   "v": "ROS / ROS 2 (Humble, Jazzy) · MoveIt 2 · Nav2 · Gazebo · RViz · Isaac Sim · MuJoCo · Autoware"
  },
  {
   "k": "Planning",
   "v": "A* · Theta* · SMAC · RRT / RRT-Connect · BIT* · DWA · Pure Pursuit · Stanley · TEB · MPPI"
  },
  {
   "k": "Physical AI",
   "v": "ACT · Diffusion Policy · smolVLA · π0.5 / openpi · flow matching · GRPO · inverse RL (MaxEnt) · sim-to-real transfer"
  },
  {
   "k": "Perception",
   "v": "YOLO · OpenCV · depth estimation · sensor fusion · OctoMap · visual SLAM (PySLAM)"
  },
  {
   "k": "Hardware",
   "v": "UR12e / UR5 · Robotiq Hand-E & 2F-85 · TurtleBot3/4 · Unitree Go2 · Jetson Nano · Arduino"
  },
  {
   "k": "Sensors",
   "v": "LiDAR · IMU · wheel encoders · Intel RealSense D435i · GPS/GNSS RTK"
  },
  {
   "k": "Languages",
   "v": "Python · C++ · C · URDF / XACRO · CMake"
  },
  {
   "k": "Design",
   "v": "SolidWorks · OnShape · Eagle PCB"
  }
 ],
 "path": [
  {
   "when": "2026 –",
   "title": "Advanced Robotics and AI intern Siemens",
   "body": [
    "Berkeley, California. On-site, from June 2026."
   ]
  },
  {
   "when": "2026",
   "title": "Graduate lab assistant Northeastern University",
   "body": [
    "ROS 2 bag collection from a Ford Mustang Mach-E autonomous vehicle platform, with visual SLAM run over the recorded drives for trajectory analysis. Configured the UR12e URDF with Robotiq gripper integration and built the MoveIt 2 planning stack for faculty research, plus an end-effector camera mount now used across several setups."
   ]
  },
  {
   "when": "2025 – 27",
   "title": "MS Robotics, Electrical & Computer Engineering Northeastern University",
   "body": [
    "Expected May 2027. Robotics Lab."
   ]
  },
  {
   "when": "2020 – 25",
   "title": "Team Robocon MJCET",
   "body": [
    "Junior programmer → programmer → robotics control engineer → team lead/captain → team mentor",
    "Five ABU Robocon seasons. As team lead I took the team to its first national appearance in over five years at Harvest Day (2024) — two holonomic drives with ball shooters, pneumatic seedling collection and silo placement, on a ROS stack with custom waypoint navigation, colour-based ball detection, and a learned policy that chose silo placements against the opponent’s moves.",
    "Before that: lagori (2022), an omni shooter paired with a swerve robot, computer vision tracking incoming balls and a model predicting where the stack would fall; Angkor Wat (2023), omni and mecanum platforms detecting rings and poles; and pitch-pot (2021), a holonomic chassis with pneumatic arrow handling and a spring-based shooter. Mentored the 2025 basketball season."
   ]
  },
  {
   "when": "2020 – 24",
   "title": "BE Computer Science & Engineering Osmania University",
   "body": [
    "Hyderabad, India."
   ]
  },
  {
   "when": "2022",
   "title": "Robotics engineer intern Consciente Technologies",
   "body": [
    "Computed Denavit–Hartenberg parameters for a custom 5-DOF manipulator and configured the MoveIt planning stack for integrated control. On a separate mobile robot, built a coordinate-based autonomous navigation system that took goal coordinates typed at the terminal, and deployed it on the physical base."
   ]
  }
 ],
 "contact": [
  {
   "href": "mailto:mohammedabdulr.1@northeastern.edu",
   "label": "mohammedabdulr.1@northeastern.edu"
  },
  {
   "href": "https://linkedin.com/in/abdu7rahman",
   "label": "linkedin.com/in/abdu7rahman"
  },
  {
   "href": "https://github.com/abdu7rahman",
   "label": "github.com/abdu7rahman"
  },
  {
   "href": "Resume.pdf",
   "label": "Résumé (PDF)"
  }
 ]
};
